### ISSUE TITLE
Method to upload Bytes directly

### ISSUE THREAD

**Issue by JDJGInc** [hatarist/aioimgur#2]
Mainly I want to make sure that I have a method to upload the Bytes Directly.
and not just a path or url.
Thank You :D

**Comment by hatarist** [comment]
Feel free to create a pull request with such a method. There seems to be a pretty similar one already: https://github.com/hatarist/aioimgur/blob/06a3c93ef5a4dff93cbad14922736b461c30ff14/aioimgur/client.py#L591-L603

This was a just-for-fun shitproject I converted from the original imgur's python library, which was - even then, 3 years ago -  deprecated and frozen.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/2741725/106198036-88b54f00-61c4-11eb-8a72-f8699c478548.png">

Thankfully I don't use Discord lately. You would reach out for me there, too, wouldn't ya?

**Comment by JDJGInc** [comment]
I would but I don't know what it is. I even tried looking for it.

**Comment by JDJGInc** [comment]
The issue Is I can't seem to get work with this:

sr_client=sr_api.Client(key=#key)
  source_image=sr_client.petpet(avatar=str(url))
  await sr_client.close()

  image = await source_image.read()

  imgur_client= aioimgur.ImgurClient#imgur_id,#imgur_secret)
  imgur_url = await imgur_client.upload(image)
  print(imgur_url)

**Comment by JDJGInc** [comment]
welp I have no way to fix this :(

**Comment by JDJGInc** [comment]
Please help me fix these bytes.

**Comment by hatarist** [comment]
Uploaded aioimgur==0.1.1 to PyPI.

Examples:
```python
import aiofiles, aioimgur, io


imgur = aioimgur.ImgurClient(client_id='***', client_secret='**********')


# example 1 (bytes):

async with aiofiles.open('/tmp/example.png', 'rb') as f:
    image = await f.read()

result = await imgur.upload(image)


# example 2 (async file-like objects):

async with aiofiles.open('/tmp/example.png', 'rb') as f:
    result = await imgur.upload(f)


# example 3 (file-like objects):

with open('/tmp/example.png', 'rb') as f:
    result = await imgur.upload(f)
```

Can upload videos now, too:

```python
async with aiofiles.open('/tmp/guillermo.mov', 'rb') as f:
    result = await imgur.upload(f, content_type='video')
```

**Comment by JDJGInc** [comment]
This still doesn't work with the bytes object I have.

**Comment by JDJGInc** [comment]
if you could, could we talk directly on discord?
here's it: JDJG Inc. Official#3493

**Comment by hatarist** [comment]
Won't hurt to know more about the sr_client.petpet, wtf is that? Get `ipython` or `ptpython` (it's more convenient and smart that the default interpreter), run it and try your script line-by-line there.

```python
# don't forget about the imports

sr_client = sr_api.Client(key="***")

source_image = sr_client.petpet(avatar=str(url))
# WTF is `url`? Is it publicly available? imgur client can upload images from URLs
# but alright, I guess you need it.

await sr_client.close()

# That looks kinda weird - first you close the sr_client, then you try to read the object given by that sr_client.
# You sure the image is there?
image = await source_image.read()

# If you do this (change the extension if needed):
with open('image.jpg', 'wb') as f:
    f.write(image)

# will it save an normal image? would you be able to open it elsewhere?

# What does this return?
type(image)
len(image)
```

**Comment by JDJGInc** [comment]
I suggested discord before, because I actually know the guy who made sr_api and plus there's a lot less in delay when talking on there and anyone can friend me so yeah.

**Comment by JDJGInc** [comment]
huh it should work I think now.

**Comment by JDJGInc** [comment]
Can I still get contact with you on there? if so that would be great, It also should work now.

**Comment by JDJGInc** [comment]
it does work now, but I still would like a better way to talk to the owner of the aioimgur wrapper.

**Comment by JDJGInc** [comment]
Here's my discord: JDJG Inc. Official#3493 (anyone can friend me :D) - just need to make it everyone for a bit, and then it will work.

**Comment by JDJGInc** [comment]
I have many other questions like closing a session, etc and you being in contact with me should help a lot lol.

**Comment by JDJGInc** [comment]
@hatarist uh can we do something about, besides that you can close here.
